# Generated by Django 4.2.5 on 2023-09-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vin',
            name='couleur',
            field=models.CharField(choices=[('r', 'Rouge'), ('b', 'Blanc'), ('p', 'Rose')], max_length=6),
        ),
    ]
