# Generated by Django 4.2.5 on 2023-09-23 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_alter_vin_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='vin',
            name='id_cave',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wines.cavevirtuelle'),
            preserve_default=False,
        ),
    ]
