# Generated by Django 4.2.5 on 2023-10-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0006_alter_vin_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionviticole',
            name='latitude',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regionviticole',
            name='longitude',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
