# Generated by Django 4.2.5 on 2023-10-18 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wines', '0010_evenement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='participants',
        ),
        migrations.AddField(
            model_name='evenement',
            name='participants',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
