# Generated by Django 4.2.5 on 2023-10-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0013_alter_evenement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
