# Generated by Django 4.2.5 on 2023-10-23 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wines', '0015_alter_evenement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
