# Generated by Django 4.2.5 on 2023-10-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0016_alter_evenement_participants_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_profilepic',
            field=models.BooleanField(default=False),
        ),
    ]
