# Generated by Django 4.2.5 on 2023-10-23 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0016_alter_evenement_participants_alter_photo_image'),
        ('authentication', '0003_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wines.photo'),
        ),
    ]
